# Generated by Django 4.1.7 on 2023-04-21 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product',
            new_name='product',
        ),
    ]
